
# This Makefile was generated by genmakefile.py, a Makefile generation script.
# For more information on genmakefile.py, refer to the genmakefile webpage at:
# http://www-personal.umich.edu/~gopalkri/MakefileGenerator/
# You may also contact the author of the script by email at: gopalkri@umich.edu
CC = gcc
LD = gcc

CFLAGS = `pkg-config gdk-pixbuf-2.0 --cflags` -ansi -Wall -pedantic -std=c99 -c -O2
LFLAGS = -lGL -lGLU -lglut `pkg-config gdk-pixbuf-2.0 --libs` -lm

TEXTURE_PLATFORM_SOURCES = texture_gdk.c

# Windows (cygwin)
ifeq "$(OS)" "Windows_NT"
	CFLAGS = `pkg-config gdk-pixbuf-2.0 --cflags` -Wall
	LFLAGS = -lopengl32 -lglu32 -lglut32 `pkg-config gdk-pixbuf-2.0 --libs`
	TEXTURE_PLATFORM_SOURCES = texture_gdk.c
endif
 
# OS X
ifeq "$(OSTYPE)" "darwin"
	CFLAGS = 
	LFLAGS = -framework Carbon -framework QuickTime \
			  -framework OpenGL -framework GLUT
	TEXTURE_PLATFORM_SOURCES = texture_quicktime.c
endif

OBJS = genpix.o image.o util.o texture_common.o

PROG = genpix

default: $(PROG)

$(PROG): $(OBJS)
	$(LD) $(LFLAGS) $(OBJS) -o $(PROG)

genpix.o: genpix.c genpix.h image.h util.h
	$(CC) $(CFLAGS) genpix.c

image.o: image.c texture.h util.h
	$(CC) $(CFLAGS) image.c

util.o: util.c util.h
	$(CC) $(CFLAGS) util.c

texture_common.o: texture.h texture_common.c
	$(CC) $(CFLAGS) --combine texture_common.c $(TEXTURE_PLATFORM_SOURCES)

clean:
	rm -rf *.o

real_clean:
	 rm -rf *.o $(PROG)

